<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Planner.Core\Planner.Core.csproj" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.30" />
    <PackageReference Include="Cronos" Version="0.13.0" />
  </ItemGroup>
</Project>
